config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'moderated_models#index'
  resources :moderated_models
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/moderable.rb
module Moderable
  extend ActiveSupport::Concern

  included do
      def status?
      response =  RestClient.get "https://moderation.logora.fr/predict?text=#{content}",
      {content_type: :json, accept: :json}
      prediction = JSON.parse(response)
        if prediction["prediction"]["0"] <= 0.1669644832611084
            self.update!(is_accepted: false)
        else
            self.update!(is_accepted: true)
        end
      end
  end
end

app/models/moderated_model.rb
class ModeratedModel < ApplicationRecord
  include Moderable
  after_create :status?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moderated_models_controller.rb
class ModeratedModelsController < ApplicationController
  before_action :set_moderated_model, only: %i[ show edit update destroy ]

  def index
    @moderated_models = ModeratedModel.all.order("created_at ASC")
  end

  def show
  end

  def new
    @moderated_model = ModeratedModel.new
  end

  def edit
  end

  def create
    @moderated_model = ModeratedModel.new(moderated_model_params)

    if @moderated_model.save!
      redirect_to moderated_models_path(@moderated_model)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @moderated_model.update(moderated_model_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @moderated_model.destroy
    redirect_to moderated_models_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_moderated_model
    @moderated_model = ModeratedModel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def moderated_model_params
    params.require(:moderated_model).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moderated_models_helper.rb
module ModeratedModelsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ModeratedModel</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "New", new_moderated_model_path, class:"nav-link btn btn-dark text-white" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModerationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/moderated_models/_form.html.erb
<%= form_with(model: moderated_model) do |form| %>
    <% if moderated_model.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(moderated_model.errors.count, "error") %> prohibited this moderated model from being saved:</h2>

        <ul>
          <% moderated_model.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class=" align-items-center d-flex flex-column mb-3">
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content, class:"form-control w-50 mt-2", placeholder:"Type content here..."%>
    </div>

    <div>
      <%= form.submit "Save", class:"btn btn-success" %> |
      <%= link_to "Back", moderated_models_path, class:"btn btn-dark" %>
    </div>
  <% end %>
  

app/views/moderated_models/_moderated_model.html.erb
<div id="<%= dom_id moderated_model %>">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h2 class="display-6 text-muted">Content</h2>
      <p class="lead"><%= moderated_model.content %></p>
      <h4 class="text-muted">Status:</h4>
      <p class="lead"><%= moderated_model.is_accepted ? "Accepted" : "Rejected" %></p>
      <%= link_to "Edit", edit_moderated_model_path(@moderated_model), class:"btn btn-success" %> |
      <%= link_to "Back", moderated_models_path, class:"btn btn-dark" %>
    </div>

  </div>
</div>

app/views/moderated_models/edit.html.erb
<div class="container text-center d-flex flex-column justify-content-center mt-3">
  <h2>Editing moderated model </h1>
  <%= render "form", moderated_model: @moderated_model %>
</div>

app/views/moderated_models/index.html.erb
<div class="container-fluid mt-3">
    <div class="container">
    <% if @moderated_models.present? %>
        <table class="table table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Content</th>
                    <th>Accepted Status</th>
                    <th colspan="2">Actions</th>
                </tr>
            </thead>
            <tbody>
            <% @moderated_models.each do |moderated_model| %>
                <tr>
                    <td><%= moderated_model.id %></td>
                    <td class="text-dark" style="max-width: 300px;"><%= moderated_model.content %></td>
                    <td><%= moderated_model.is_accepted ? "Accepted" : "Rejected" %></td>
                    <td><%= link_to "Show", moderated_model, class:"btn btn-dark" %></td>
                    <td><%= button_to "Destroy", moderated_model, method: :delete, class:"btn btn-dark" %></td>

                </tr>
            <% end %>
            </tbody>
        </table>
    <% else %>
            <h4 class="display-6 text-center">No Content To Show :( </h4>
    <% end %>
    </div>
</div>

app/views/moderated_models/new.html.erb
<div class="container text-center d-flex flex-column justify-content-center">
  <h2>New Moderated Model</h2>
  <%= render "form", moderated_model: @moderated_model %>
</div>

app/views/moderated_models/show.html.erb
<div class="mt-3">
    <%= render @moderated_model %>
</div>